# Generated by Django 4.1 on 2022-11-24 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ticketingtoolapp', '0003_user_delete_adminpage_delete_employee_delete_manager'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Organisation',
        ),
    ]
